name: graphical
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  path: ^1.8.1
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.1
  pedantic: ^1.11.1
